name: makhber
summary: Makhber
description: |
  Application for Visualization and Analysis of Scientific Data
# icon: packaging/freedesktop/com.github.makhber.Makhber.svg
# website: https://github.com/Makhber/makhber
# issues: https://github.com/Makhber/makhber/issues
base: core20
compression: lzo
grade: stable
confinement: strict
adopt-info: makhber
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  makhber:
    common-id: com.github.makhber.Makhber
    command: usr/bin/makhber
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.8/site-packages
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - removable-media
      - unity7

parts:
  makhber:
    source-type: local
    source: .
    parse-info: [usr/share/metainfo/com.github.makhber.Makhber.appdata.xml]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DMAKHBER_SCRIPTING_PYTHON=ON"
      - "-DMAKHBER_SEARCH_FOR_UPDATES=OFF"
      - "-DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr"
      - "-DPyQt_INCLUDE_DIR=$SNAPCRAFT_STAGE/usr/lib/python3.8/site-packages/PyQt5/bindings"
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - LD_LIBRARY_PATH: /snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBARARY_PATH
      - PYTHONPATH: $SNAPCRAFT_STAGE/usr/lib/python3.8/site-packages:$HOME/.local/lib/python3.8/site-packages:/usr/local/lib/python3.8/dist-packages
    build-packages:
      - g++
      - libglu1-mesa
      - git
    stage-packages:
      - libpython3.8
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    after:
      - gsl
      - muparser
      - gl2ps
      - pyqt5
      - pyqt5-sip
  gsl:
    source-type: tar
    source: https://ftp.gnu.org/gnu/gsl/gsl-2.7.1.tar.gz
    source-checksum: sha256/dcb0fbd43048832b757ff9942691a8dd70026d5da0ff85601e52687f6deeb34b
    plugin: autotools
    autotools-configure-parameters:
      - "--disable-static"
      - "--prefix=/usr"
    build-packages:
      - g++
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - -usr/share
  muparser:
    source-type: tar
    source: https://github.com/beltoforion/muparser/archive/v2.3.3-1.tar.gz
    source-checksum: sha256/91d26d8274ae9cd9c776ee58250aeddc6b574f369eafd03b25045b858a2b8177
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
  gl2ps:
    source-type: tar
    source: https://geuz.org/gl2ps/src/gl2ps-1.4.2.tgz
    source-checksum: sha256/8d1c00c1018f96b4b97655482e57dcb0ce42ae2f1d349cd6d4191e7848d9ffe9
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    prime:
      - -usr/lib/libgl2ps.a
      - -usr/include
      - -usr/share
  pyqt5:
    source-type: tar
    source: https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.15.6.tar.gz
    source-checksum: sha256/80343bcab95ffba619f2ed2467fd828ffeb0a251ad7225be5fc06dcc333af452
    plugin: make
    build-packages:
      - g++
      - libgl-dev
      - libgles-dev
      - python3-pip
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - LD_LIBRARY_PATH: /snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBARARY_PATH
    override-build: |
      pip3 install sip pyqt-builder
      cd $SNAPCRAFT_PART_SRC
      sip-build --confirm-license \
        --build-dir ../build \
        --target-dir $SNAPCRAFT_PART_INSTALL/usr/lib/python3.8/site-packages \
        --qmake=/snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current/usr/lib/qt5/bin/qmake \
        --concatenate $(nproc) \
        --no-make \
        --no-tools \
        --no-designer-plugin \
        --no-qml-plugin \
        --disable QtQml \
        --disable QtBluetooth \
        --disable QtDBus \
        --disable QtDesigner \
        --disable QtHelp \
        --disable QtMultimedia \
        --disable QtMultimediaWidgets \
        --disable QtNfc \
        --disable QtRemoteObjects \
        --disable QtPositioning \
        --disable QtLocation \
        --disable QtQuick \
        --disable QtQuickWidgets \
        --disable QtSensors \
        --disable QtSerialPort \
        --disable QtSql \
        --disable QtTest \
        --disable QtTextToSpeech \
        --disable QtWebChannel \
        --disable QtWebKit \
        --disable QtWebKitWidgets \
        --disable QtWebSockets \
        --disable QtX11Extras \
        --disable QtXml \
        --disable QtXmlPatterns \
        --verbose
      cd $SNAPCRAFT_PART_BUILD
      snapcraftctl build
    prime:
      - -usr/lib/python3.8/site-packages/PyQt5/bindings
  pyqt5-sip:
    plugin: python
    python-packages:
      - pyqt5-sip
      - --no-deps
      - --target=$SNAPCRAFT_PART_INSTALL/usr/lib/python3.8/site-packages
    prime:
      - -bin/
      - -lib/
      - -share/
