name: makhber
summary: Makhber
description: |
  Application for Visualization and Analysis of Scientific Data
# icon: packaging/freedesktop/com.github.makhber.Makhber.svg
# website: https://github.com/Makhber/makhber
# issues: https://github.com/Makhber/makhber/issues
base: core22
compression: lzo
grade: stable
confinement: strict
adopt-info: makhber
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x

apps:
  makhber:
    common-id: com.github.makhber.Makhber
    command: bin/desktop-launch $SNAP/usr/bin/makhber
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - home
      - network
      - removable-media
      - unity7
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11

parts:
  makhber:
    source-type: local
    source: .
    parse-info: [usr/share/metainfo/com.github.makhber.Makhber.appdata.xml]
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DBUILD_SHARED_LIBS=ON"
      - "-DMAKHBER_SCRIPTING_PYTHON=ON"
      - "-DMAKHBER_SEARCH_FOR_UPDATES=OFF"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE/usr"
      - "-DPYTHON_INSTALL_PATH=lib/python3/dist-packages"
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$HOME/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages
    build-packages:
      - g++
      - git
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - qttools5-dev
      - pkgconf
    stage-packages:
      - libglu1-mesa
      - libpython3.10
      - libqt5svg5
      - libqt5opengl5
      - libqt5printsupport5
      - qttranslations5-l10n
      - qtwayland5
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    after:
      - desktop-qt5
      - gsl
      - muparser
      - gl2ps
      - pyqt5
      - pyqt5-sip
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
  gsl:
    source-type: tar
    source: https://ftp.gnu.org/gnu/gsl/gsl-2.8.tar.gz
    source-checksum: sha256/6a99eeed15632c6354895b1dd542ed5a855c0f15d9ad1326c6fe2b2c9e423190
    plugin: autotools
    autotools-configure-parameters:
      - "--disable-static"
      - "--prefix=/usr"
    build-packages:
      - g++
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - -usr/share
  muparser:
    source-type: tar
    source: https://github.com/beltoforion/muparser/archive/v2.3.4.tar.gz
    source-checksum: sha256/0c3fa54a3ebf36dda0ed3e7cd5451c964afbb15102bdbcba08aafb359a290121
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    stage-packages:
      - libgomp1
    prime:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
      - -usr/share
  gl2ps:
    source-type: tar
    source: https://geuz.org/gl2ps/src/gl2ps-1.4.2.tgz
    source-checksum: sha256/8d1c00c1018f96b4b97655482e57dcb0ce42ae2f1d349cd6d4191e7848d9ffe9
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - g++
    stage-packages:
      - libgl1
      - libpng16-16
    prime:
      - -usr/lib/libgl2ps.a
      - -usr/include
      - -usr/share
  pyqt5:
    source-type: tar
    source: https://pypi.python.org/packages/source/P/PyQt5/PyQt5-5.15.11.tar.gz
    source-checksum: sha256/fda45743ebb4a27b4b1a51c6d8ef455c4c1b5d610c90d2934c7802b5c1557c52
    plugin: make
    build-packages:
      - g++
      - libgl-dev
      - libgles-dev
      - libpython3-dev
      - python3-pip
    stage-packages:
      - libqt5svg5
      - libqt5opengl5
      - libqt5printsupport5
    build-environment:
      - PATH: $HOME/.local/bin:$PATH
    override-build: |
      pip3 install sip pyqt-builder
      cd $CRAFT_PART_SRC
      sip-build --confirm-license \
        --build-dir ../build \
        --target-dir $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages \
        --no-make \
        --no-tools \
        --no-designer-plugin \
        --no-qml-plugin \
        --disable QtBluetooth \
        --disable QtDBus \
        --disable QtDesigner \
        --disable QtHelp \
        --disable QtLocation \
        --disable QtMultimedia \
        --disable QtMultimediaWidgets \
        --disable QtNfc \
        --disable QtPositioning \
        --disable QtQml \
        --disable QtQuick \
        --disable QtQuickWidgets \
        --disable QtRemoteObjects \
        --disable QtSensors \
        --disable QtSerialPort \
        --disable QtSql \
        --disable QtTest \
        --disable QtTextToSpeech \
        --disable QtWebChannel \
        --disable QtWebKit \
        --disable QtWebKitWidgets \
        --disable QtWebSockets \
        --disable QtX11Extras \
        --disable QtXml \
        --disable QtXmlPatterns \
        --verbose
      cd $CRAFT_PART_BUILD
      craftctl default
    prime:
      - -usr/lib/python3/dist-packages/PyQt5/bindings
  pyqt5-sip:
    plugin: nil
    build-packages:
      - python3-pip
    override-build:
      pip3 install pyqt5-sip --no-deps --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
